# Generated by Django 3.1 on 2021-08-15 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата модификации')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='заголовок объекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание объекта')),
                ('sort', models.IntegerField(blank=True, default=0, verbose_name='номер объекта для сортировки')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Активен ли объект')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'ordering': ('sort', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Manufacturies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата модификации')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='заголовок объекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание объекта')),
                ('sort', models.IntegerField(blank=True, default=0, verbose_name='номер объекта для сортировки')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Активен ли объект')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производитель',
                'db_table': 'manufacturer',
                'ordering': ('sort', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата модификации')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='заголовок объекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание объекта')),
                ('sort', models.IntegerField(blank=True, default=0, verbose_name='номер объекта для сортировки')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Активен ли объект')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.ManyToManyField(blank=True, related_name='products_set', to='products.Categories', verbose_name='category')),
                ('manufacture', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.manufacturies')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'products',
                'ordering': ('sort', 'title'),
            },
        ),
        migrations.CreateModel(
            name='MotherBoardsProduct',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.products')),
                ('socket', models.CharField(max_length=100, verbose_name='Сокет')),
                ('chipset', models.CharField(max_length=100, verbose_name='Чипсет')),
                ('frequency_memory', models.SmallIntegerField(verbose_name='Частота памяти')),
                ('num_memory_slots', models.SmallIntegerField(verbose_name='Количество слотов памяти')),
                ('form_factor', models.CharField(max_length=100, verbose_name='Форм-фактор')),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнские платы',
                'db_table': 'motherboards_products',
                'ordering': ('sort', 'title'),
            },
            bases=('products.products',),
        ),
        migrations.CreateModel(
            name='ProductPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pictures')),
                ('related_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='pictures')),
            ],
            options={
                'db_table': 'pictures',
            },
        ),
        migrations.CreateModel(
            name='ProcessorsProduct',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.products')),
                ('core', models.CharField(max_length=100, verbose_name='Ядро')),
                ('socket', models.CharField(max_length=100, verbose_name='Сокет')),
                ('num_cores', models.SmallIntegerField(verbose_name='Количество ядер')),
                ('num_threads', models.SmallIntegerField(verbose_name='Количество потоков')),
                ('frequency', models.SmallIntegerField(verbose_name='Частота')),
                ('lithorgaphy', models.SmallIntegerField(verbose_name='Количество слотов памяти')),
                ('memory_type', models.CharField(max_length=100, verbose_name='Тип памяти')),
                ('graphics_core', models.CharField(max_length=100, verbose_name='Сокет')),
                ('num_memory_channels', models.SmallIntegerField(verbose_name='Количество слотов памяти')),
                ('pci_express_version', models.SmallIntegerField(verbose_name='Версия PCI-Express')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_set', to='products.manufacturies')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
                'db_table': 'processors_products',
                'ordering': ('sort', 'title'),
            },
            bases=('products.products',),
        ),
    ]
